###### NETWORK CONFIG ######
networks:                           # Network interface configuration
  proxy-redirect:                   # Reference 'proxy-redirect' as predefined network
    external:                       # Note: Please create the network manually as it is preexisting on Industrial Edge Device
      name: proxy-redirect
    driver: bridge