#ifndef ACTIONS_CONST
#define ACTIONS_CONST

#define DISSEMINATOR_ACTION_UPLINK_NO_ACK "disUPn"
#define DISSEMINATOR_ACTION_DOWNLINK_NO_ACK "disDWn"
#define DISSEMINATOR_ACTION_ERRORS "disERR"
#define DISSEMINATOR_ACTION_MESSAGES "disMSG"
#define DISSEMINATOR_ACTION_BROADCAST_ALERTS "disbALT"

#define ACTION_UPLINK_NO_ACK "UPn"
#define ACTION_DOWNLINK_NO_ACK "DWn"
#define ACTION_JOIN_REQUEST "JR"
#define ACTION_JOIN_ACCEPT "JA"
#define ACTION_RADIO_SEND "RUS"
#define ACTION_RADIO_RECEIVE "RDR"

#endif